export const sampleProperties = [
    {
      id: 1,
      title: 'Cozy Beach House',
      description: 'A beautiful house near the beach with stunning ocean views.',
      location: 'Malibu, CA',
      price: 300,
      imageUrl: 'https://images.pexels.com/photos/1861485/pexels-photo-1861485.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 2,
      title: 'Charming Cabin',
      description: 'A rustic cabin in the woods, perfect for a peaceful getaway.',
      location: 'Lake Tahoe, NV',
      price: 250,
      imageUrl: 'https://images.pexels.com/photos/1861485/pexels-photo-1861485.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 3,
      title: 'Modern Apartment',
      description: 'A stylish apartment in the city center, close to all attractions.',
      location: 'New York, NY',
      price: 500,
      imageUrl: 'https://images.pexels.com/photos/276513/pexels-photo-276513.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 4,
      title: 'Luxury Villa',
      description: 'A luxury villa with private pool and breathtaking views.',
      location: 'Bali, Indonesia',
      price: 800,
      imageUrl: 'https://images.pexels.com/photos/3587396/pexels-photo-3587396.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 5,
      title: 'Quaint Cottage',
      description: 'A quaint cottage in a serene village, ideal for relaxation.',
      location: 'Charleston, SC',
      price: 200,
      imageUrl: 'https://images.pexels.com/photos/3707066/pexels-photo-3707066.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 6,
      title: 'Spacious Farmhouse',
      description: 'A spacious farmhouse with a large garden and beautiful scenery.',
      location: 'Napa Valley, CA',
      price: 450,
      imageUrl: 'https://images.pexels.com/photos/209840/pexels-photo-209840.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 8,
      title: 'Elegant Townhouse',
      description: 'An elegant townhouse with vintage decor and cozy atmosphere.',
      location: 'Boston, MA',
      price: 350,
      imageUrl: 'https://images.pexels.com/photos/3707066/pexels-photo-3707066.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 9,
      title: 'Oceanfront Resort',
      description: 'An oceanfront resort with stunning views and top-notch facilities.',
      location: 'Honolulu, HI',
      price: 900,
      imageUrl: 'https://images.pexels.com/photos/1552874/pexels-photo-1552874.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      id: 10,
      title: 'Chic City Apartment',
      description: 'A chic apartment in a vibrant neighborhood with nightlife.',
      location: 'Los Angeles, CA',
      price: 600,
      imageUrl: 'https://images.pexels.com/photos/276513/pexels-photo-276513.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
  ];
  